In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_Vacation.csv")
vacation_df.head(50)

,City_ID,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,0,Puerto Ayora,EC,76.96,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
1,1,Acajutla,SV,84.99,moderate rain,13.5928,-89.8275,NaN
2,2,Bluff,NZ,50.45,overcast clouds,-46.6000,168.3333,NaN
3,3,Tiznit,MA,88.12,overcast clouds,29.5833,-9.5000,NaN
4,4,Hualmay,PE,68.16,broken clouds,-11.0964,-77.6139,Hotel Villa Kitzia Huacho
5,5,Cuencame,MX,80.80,clear sky,24.8711,-103.6964,HOTEL RICOME
6,6,Constitucion,CL,56.66,heavy intensity rain,-35.3333,-72.4167,NaN
7,7,Eldorado,BR,68.23,few clouds,-23.7869,-54.2836,NaN
8,8,Valparaiso,CL,64.63,clear sky,-33.0393,-71.6273,Hotel Ultramar
9,9,Albany,US,88.27,scattered clouds,42.6001,-73.9662,NaN
10,10,Laguna,US,74.43,clear sky,38.4210,-121.4238,NaN
11,11,Qarchi Gak,AF,70.68,overcast clouds,37.0400,66.7889,NaN
12,12,Pudozh,RU,47.57,few clouds,61.8099,36.5345,Guest-House na Transportnoy
13,13,Srednekolymsk,RU,47.73,overcast clouds,67.4500,153.6833,NaN
14,14,Victoria,HK,79.18,overcast clouds,22.2855,114.1577,NaN
15,15,Mnogovershinnyy,RU,28.47,overcast clouds,53.9353,139.9242,Obshchezhitiye 14
16,16,Tuktoyaktuk,CA,27.88,scattered clouds,69.4541,-133.0374,End of The Road Ltd.
17,17,Bethel,US,87.98,few clouds,41.3712,-73.4140,Courtyard by Marriott Danbury
18,18,Yellowknife,CA,36.12,light rain,62.4560,-114.3525,NaN
19,19,Mar Del Plata,AR,60.94,overcast clouds,-38.0023,-57.5575,NaN
20,20,Longyearbyen,SJ,37.24,broken clouds,78.2186,15.6401,NaN
21,21,Ambon,ID,77.14,light rain,-3.6954,128.1814,NaN
22,22,Sanandaj,IR,71.94,broken clouds,35.3144,46.9923,NaN
23,23,Butaritari,KI,80.60,moderate rain,3.0707,172.7902,NaN
24,24,Soyo,AO,78.24,broken clouds,-6.1349,12.3689,NaN
25,25,Aklavik,CA,26.60,light snow,68.2191,-135.0107,NaN
26,26,Castro,BR,65.82,clear sky,-24.7911,-50.0119,NaN
27,27,Ushuaia,AR,33.46,few clouds,-54.8000,-68.3000,NaN
28,28,Port Alfred,ZA,59.18,scattered clouds,-33.5906,26.8910,NaN
29,30,Mahebourg,MU,75.49,scattered clouds,-20.4081,57.7000,NaN
30,31,Rikitea,PF,75.96,clear sky,-23.1203,-134.9692,NaN
31,32,Vaini,TO,75.36,scattered clouds,-21.2000,-175.2000,NaN
32,33,Port Hedland,AU,77.05,overcast clouds,-20.3167,118.5667,NaN
33,34,Souillac,MU,75.58,scattered clouds,-20.5167,57.5167,NaN
34,35,Alofi,NU,79.07,light rain,-19.0595,-169.9187,NaN
35,36,Sorland,NO,48.06,overcast clouds,67.6670,12.6934,NaN
36,37,Omsukchan,RU,31.06,overcast clouds,62.5333,155.8000,NaN
37,38,Hobart,AU,49.86,overcast clouds,-42.8794,147.3294,NaN
38,39,Port Elizabeth,ZA,62.10,broken clouds,-33.9180,25.5701,NaN
39,40,Touros,BR,83.25,scattered clouds,-5.1989,-35.4608,NaN
40,41,San Cristobal,VE,78.98,few clouds,7.7669,-72.2250,NaN
41,42,Salalah,OM,84.29,broken clouds,17.0151,54.0924,NaN
42,43,La Baule-Escoublac,FR,80.26,clear sky,47.2922,-2.3640,NaN
43,44,Gat,IL,74.08,clear sky,31.6100,34.7642,NaN
44,45,Ancud,CL,48.61,light rain,-41.8697,-73.8203,NaN
45,46,Qaanaaq,GL,23.85,overcast clouds,77.4840,-69.3632,NaN
46,47,Kavaratti,IN,83.55,overcast clouds,10.5669,72.6420,NaN
47,48,Severo-Kurilsk,RU,40.42,overcast clouds,50.6789,156.1250,NaN
48,49,Porto Novo,BJ,83.93,overcast clouds,6.4965,2.6036,NaN
49,50,Harper,LR,79.00,overcast clouds,4.3750,-7.7169,NaN

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<d1>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<d1>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
<d1>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [10]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center = (30.0, 31.0), zoom_level = 1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Suzun"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Suzun"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Kupino"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Moshkovo"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Guryevsk"]
vacation_stop1

,City_ID,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
177,179,Kupino,RU,56.35,overcast clouds,54.3663,77.2981,NaN

In [12]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [14]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps.datasets

gmaps.configure(api_key = g_key)

fig = gmaps.figure()

driving_map = gmaps.directions_layer(start,end,waypoints = [stop1, stop2, stop3],travel_mode = "DRIVING")
fig.add_layer(driving_map)
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,605,Meadow Lake,US,74.7,few clouds,34.8014,-106.5436,NaN

In [ ]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<d1>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description} and {Max Temp} °F</dd>
<d1>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]
#hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]

fig = gmaps.figure(center = (30.0, 31.0), zoom_level = 1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))